[package]
name = "my_project"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "my_project"
path = "main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
iced = "0.10.0"
pnet = "0.34.0"
pcap = "0.8"
if-addrs = "0.6.5"
regex = "1.5.4"
